### ISSUE TITLE
PIEWI-5- Requests screen

### ISSUE THREAD

**Issue by jpienko** [jpienko/angular#9]
Należy wykonać następujące kroki:
- stworzyć komponent requests
- stworzyć klasy modelowe
- komponent ma wyświetlać listę złożonych wniosków
- zaktualizować routing
- widok ma być repsonsywny
- widok ma wykorzystywać komponenty z angular material (https://material.angular.io/components/table/overview)
 - komponent ma wyświetlać dane z mocka 
Klasa modelowa: BaseRequest
Właściwości: 
 - id
 - name
 - createDate
 - updateData
 - owner	
 - description
 - status (enum ze statusami wniosku)
Klasa: HolidatyRequest
Właściwości:
 - type (enum z typami urlopów)
 - from
 - to
 - replacement

**Comment by zszeligowski** [comment]
struktura projektu:
- wszystkie klasy i komponenty związane z requests powinny być w katalogu requests, nie wolno wrzucać klas i plików kodu komponentów bezpośrednio do katalogu głównego app (!) 
- holidaty-request ? - trzeba poprawić nazwe,
- komponent requests - zmień nazwe na requests-history i umieść w katalogu requests\requests-history
- enumy status i type - maja nic nieznaczące nazwy - zmień je i tez powinny być w requests bo dotyczą requests - kod, nazwy i struktura projektu powinny być samodokumentujące się (!), nic nie powinno być przypadkowe, wszystko powinno być jasne po jednym rzucie okiem 

struktura kodu:
- nadużywasz typu any - to jest niebezpieczne, technologia daje Ci silne narzędzia wykrywania błędów juz na etapie komipilacji, a Ty ich nie używasz (!),
- metody - nie deklarujesz widoczności klas i zmiennych - uwaga jw. (!)  
- ngOnInit(), ngOnDestroy() - zawsze na początku kodu klasy pod konstruktorem, chodzi o to żeby od razu widzieć co sie dzieje po załadowaniu / przy niszczeniu klasy.

funkcjonalnie:
- lista wniosków powinna się wyświetlać po naciśnięciu przycisku history, a nie w widoku głównym,
- lista źle się wyświetla w widoku mobile - trzeba dostosować styl wyświetlania i zakres danych dla wyświetlacza urządzenia mobile w rożnych rozdzielczościach,
